name: Deploy on server

on:
  push:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Lint
        run: |
            cd client
            npx astro check

      - name: Download golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Check dependencies
        run: |
          cd server
          go mod tidy

      - name: Testing server
        run: |
          cd server
          go test ./test/... -v

  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: success()

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PATH_STORAGE: ${{ secrets.PATH_STORAGE }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: SECRET_KEY,DB_NAME,PATH_STORAGE,SERVER_IP
          script: |
            cd Tasks/fileserver
            git pull
            docker compose down
            docker compose pull
            docker compose up --build -d
            docker system prune -f
