name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: cd client && npm clean-install
      - name: Lint
        run: |
            cd client 
            npx astro check
